version: '3.7'

services:
  auth:
    build: ./
    volumes:
      - .:/app/
    expose:
      - 8001
    depends_on:
      - auth_db
    networks:
      - crayons
  auth_db:
    image: postgres:12.0-alpine
    volumes:
      - auth_data:/var/lib/postgresql/data/
    ports:
      - 9001:5432
    env_file:
      - ./.env
    networks:
      - crayons

volumes:
  auth_data:

networks:
  crayons:
    name: crayons
    driver: bridge
